//! Raw FFI bindings for the CUDA runtime API.
//!
//! Generated by `pegaflow-transfer/build.rs` when the `v2` feature is on.
#![allow(warnings)]

include!(concat!(env!("OUT_DIR"), "/cudart-bindings.rs"));
