//! Raw FFI bindings for GDRCopy (`gdrapi`).
//!
//! Generated by `pegaflow-transfer/build.rs` when the `v2` feature is on.
#![allow(warnings)]

include!(concat!(env!("OUT_DIR"), "/gdrapi-bindings.rs"));
